services:
  # 第2章: 自社コーポレートサイト
  frontend-corp:
    # NOTE: 本サイトの実装が完了するまでダミーサイトを表示します
    container_name: corporate-site
    image: dummy:latest
    build:
      context: ./services/dummy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.corp.rule=Host(`${base_domain}`)"
      - "traefik.http.routers.corp.entrypoints=${entrypoints}"
      # - "traefik.http.routers.corp.tls.certresolver=${certresolver}"
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.corporate
    networks:
      - app-network
    restart: always

  # 第3章: ライバー向けランキングサイト
  frontend-rank:
    # NOTE: 本サイトの実装が完了するまでダミーサイトを表示します
    container_name: tiktok-ranking
    image: tiktok-ranking:latest
    extra_hosts:
      - "auth.${base_domain}:host-gateway"
      - "ranking.${base_domain}:host-gateway"
    build:
      context: ./services/tiktok-ranking
    volumes:
      - ./data/:/app/public/data:ro
      - ./secrets/service-account.json:/app/secrets/service-account.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rank.rule=Host(`ranking.${base_domain}`)"
      - "traefik.http.routers.rank.entrypoints=${entrypoints}"
      # - "traefik.http.routers.rank.tls.certresolver=${certresolver}"
    env_file:
      - ./secrets/.env.ranking
    networks:
      - app-network
    restart: always

  # 第4章: データ抽出 Worker
  worker-fetcher:
    container_name: data-fetcher
    image: data-fetcher:latest
    profiles: ["task"]
    build:
      context: ./services/data-fetcher/data-fetcher
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./secrets/service-account.json:/app/secrets/service-account.json:ro
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.fetcher
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  data-creators: