services:
  # 第2章: 自社コーポレートサイト
  frontend-corp:
    # NOTE: 本サイトの実装が完了するまでダミーサイトを表示します
    container_name: corporate-site
    image: dummy:latest
    build:
      context: ./services/dummy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.corp.rule=Host(`${base_domain}`)"
      - "traefik.http.routers.corp.entrypoints=web"
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.corporate
    networks:
      - app-network
    restart: always

  # 第3章: ライバー向けランキングサイト
  frontend-rank-prod:
    container_name: tiktok-ranking-prod
    image: ghcr.io/tiktok-ranking/tiktok-ranking:v0.2.0
    extra_hosts:
      - "auth.${base_domain}:host-gateway"
      - "ranking.${base_domain}:host-gateway"
    volumes:
      - ${LIVE_DATA_PATH}:/app/public/data:ro
      - ./secrets/service-account.json:/app/secrets/service-account.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rank-prod.rule=Host(`ranking.${base_domain}`)"
      - "traefik.http.routers.rank-prod.entrypoints=web"

      - "traefik.http.services.rank-prod.loadbalancer.server.port=3000"
    env_file:
      - ./secrets/.env.ranking
    networks:
      - app-network
    restart: always

  frontend-rank-next:
    container_name: tiktok-ranking-next
    image: ghcr.io/tiktok-ranking/tiktok-ranking:v0.2.1
    build:
      context: ./services/tiktok-ranking
      args:
        - NEXT_PUBLIC_KEYCLOAK_URL=http://auth.${base_domain}/realms/ranking
        - NEXT_PUBLIC_AUTH_ENABLED=${NEXT_PUBLIC_AUTH_ENABLED}
    extra_hosts:
      - "auth.${base_domain}:host-gateway"
      - "ranking.${base_domain}:host-gateway"
    volumes:
      - ${LIVE_DATA_PATH}:/app/public/data:ro
      - ./secrets/service-account.json:/app/secrets/service-account.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rank-next.rule=Host(`ranking-next.${base_domain}`)"
      - "traefik.http.routers.rank-next.entrypoints=web"

      - "traefik.http.services.rank-next.loadbalancer.server.port=3000"
    env_file:
      - ./secrets/.env.ranking
    networks:
      - app-network
    restart: always


  # 第4章: データ抽出 Worker
  worker-fetcher:
    container_name: data-fetcher
    image: data-fetcher:latest
    profiles: ["task"]
    build:
      context: ./services/data-fetcher
    volumes:
      - ${LIVE_DATA_PATH}:/app/data
      - ./logs:/app/logs
      - ./secrets/service-account.json:/app/secrets/service-account.json:ro
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.fetcher
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  data-creators: