services:
  # 第1章 1.1 & 1.2: Nginx によるリバースプロキシ
  reverse-proxy:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend-corp
      - frontend-rank
    networks:
      - app-network
    restart: always

  # 第2章: 自社コーポレートサイト
  frontend-corp:
    # NOTE: 本サイトの実装が完了するまでダミーサイトを表示します
    container_name: corporate-site
    build:
      context: ./services/dummy
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.corporate
    networks:
      - app-network
    restart: always

  # 第3章: ライバー向けランキングサイト
  frontend-rank:
    # NOTE: 本サイトの実装が完了するまでダミーサイトを表示します
    container_name: tiktok-ranking
    build:
      context: ./services/dummy
    volumes:
      - ./data/creators:/app/data:ro
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
    networks:
      - app-network
    restart: always

  # 第4章: データ抽出 Worker
  worker-fetcher:
    container_name: data-fetcher
    profiles: ["task"]
    build:
      context: ./services/data-fetcher/data-fetcher
    volumes:
      - ./data/creators:/app/data
      - ./data-fetcher/profile:/app/profile
      - ./logs:/app/logs
    env_file:
      - ./secrets/.env.common
      - ./secrets/.env.google
      - ./secrets/.env.fetcher
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-creators: